/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_myrddin_hellojni_HelloJNI */

#ifndef _Included_fr_myrddin_hellojni_HelloJNI
#define _Included_fr_myrddin_hellojni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_myrddin_hellojni_HelloJNI
 * Method:    jniGiveMeANumber
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_fr_myrddin_hellojni_HelloJNI_jniGiveMeANumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
